name: Compilar Otto-task EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clonando el ADN del proyecto
        uses: actions/checkout@v4

      - name: Motor Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalando TODO el Sistema
        run: |
          pip install django pyinstaller pywebview dj-database-url django-allauth djangorestframework requests pillow whitenoise psycopg2-binary google-cloud PyJWT cryptography oauthlib requests-oauthlib sqlparse pytz asgiref

      - name: Fabricando el .EXE
        run: |
          # Buscamos manage.py en la raiz o en la carpeta Core
          if (Test-Path "manage.py") {
            pyinstaller --noconsole --onefile --name "Otto-Task-OS" manage.py
          } elseif (Test-Path "Core/manage.py") {
            pyinstaller --noconsole --onefile --name "Otto-Task-OS" Core/manage.py
          } else {
            $main = Get-ChildItem -Filter *.py | Select-Object -First 1
            pyinstaller --noconsole --onefile --name "Otto-Task-OS" $main.Name
          }

      - name: Entrega Final
        uses: actions/upload-artifact@v4
        with:
          name: Otto-Task-Ejecutable
          path: dist/Otto-Task-OS.exe
          
