name: Compilar Otto-task EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clonando el ADN del proyecto
        uses: actions/checkout@v4

      - name: Motor Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalando Dependencias
        run: |
          pip install django pyinstaller pywebview dj-database-url django-allauth djangorestframework requests pillow whitenoise psycopg2-binary google-cloud

      - name: Fabricando el .EXE (Motor Django)
        # Probamos primero con manage.py y luego dentro de la carpeta Core
        run: |
          if (Test-Path "manage.py") {
            pyinstaller --noconsole --onefile --name "Otto-Task-OS" manage.py
          } elseif (Test-Path "Core/manage.py") {
            pyinstaller --noconsole --onefile --name "Otto-Task-OS" Core/manage.py
          } else {
            $primerPy = Get-ChildItem -Filter *.py | Select-Object -First 1
            pyinstaller --noconsole --onefile --name "Otto-Task-OS" $primerPy.Name
          }

      - name: Entrega de Producto Final
        uses: actions/upload-artifact@v4
        with:
          name: Otto-Task-Ejecutable
          path: dist/Otto-Task-OS.exe
          path: dist/Otto-Task-OS.exe
          
